document.writeln(" <div id='footer'>");
document.writeln("<ul>");
document.writeln("  <li>");
document.writeln("      <a href='index.html'>首页</a>");
document.writeln("      <i></i>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("      <a href='productDisplay.html'>产品展示</a>");
document.writeln("      <i></i>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("      <a href='solution.html'>解决方案</a>");
document.writeln("      <i></i>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("      <a href='#' class='exper'>在线体验</a>");
document.writeln("      <i></i>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("      <a href='downloadCenter.html'>下载中心</a>");
document.writeln("      <i></i>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("      <a href='contactUs.html'>联系我们</a>");
document.writeln("      ");
document.writeln("  </li>");
document.writeln("</ul>");
document.writeln("<p>@copy上海劲易电子科技有限公司,备案号：沪ICP备17012494</p>")
document.writeln(" </div>");

